### ISSUE TITLE
error message "TypeError: 'NoneType' object is not iterable"

### ISSUE THREAD

**Issue by BWobbii** [monagrland/MB_Pipeline#24]
I tried running the pipeline using rbcL reads, but it instantly gives me the error message "TypeError: 'NoneType' object is not iterable" (see full stdout below). It works with other reads...

```
Environment with Snakemake found at ./snakemake_8
Activated conda environment.
Starting the pipeline using 12 CPU cores.
Injecting conda environment /mnt/data/homes/sickel/Dokumente/2023_PilotNestAid/singleplex/rbcL_sh/MB_Pipeline/workflow/envs/global.yaml.
/mnt/data/homes/sickel/Dokumente/2023_PilotNestAid/singleplex/rbcL_sh/MB_Pipeline/workflow/rules/paired_end.smk:125: SyntaxWarning: invalid escape sequence '\;'
/mnt/data/homes/sickel/Dokumente/2023_PilotNestAid/singleplex/rbcL_sh/MB_Pipeline/workflow/rules/paired_end.smk:136: SyntaxWarning: invalid escape sequence '\;'
Traceback (most recent call last):
  File "/mnt/data/homes/sickel/Dokumente/2023_PilotNestAid/singleplex/rbcL_sh/MB_Pipeline/snakemake_8/lib/python3.12/site-packages/snakemake/cli.py", line 1898, in args_to_api
    dag_api = workflow_api.dag(
              ^^^^^^^^^^^^^^^^^
  File "/mnt/data/homes/sickel/Dokumente/2023_PilotNestAid/singleplex/rbcL_sh/MB_Pipeline/snakemake_8/lib/python3.12/site-packages/snakemake/api.py", line 326, in dag
    return DAGApi(
           ^^^^^^^
  File "<string>", line 6, in __init__
  File "/mnt/data/homes/sickel/Dokumente/2023_PilotNestAid/singleplex/rbcL_sh/MB_Pipeline/snakemake_8/lib/python3.12/site-packages/snakemake/api.py", line 436, in __post_init__
    self.workflow_api._workflow.dag_settings = self.dag_settings
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/homes/sickel/Dokumente/2023_PilotNestAid/singleplex/rbcL_sh/MB_Pipeline/snakemake_8/lib/python3.12/site-packages/snakemake/api.py", line 383, in _workflow
    workflow.include(
  File "/mnt/data/homes/sickel/Dokumente/2023_PilotNestAid/singleplex/rbcL_sh/MB_Pipeline/snakemake_8/lib/python3.12/site-packages/snakemake/workflow.py", line 1379, in include
    exec(compile(code, snakefile.get_path_or_uri(), "exec"), self.globals)
  File "/mnt/data/homes/sickel/Dokumente/2023_PilotNestAid/singleplex/rbcL_sh/MB_Pipeline/workflow/Snakefile", line 55, in <module>
    "results/12_report/multiqc_report.{method}.{screening}.{class_method_x_refdb}.html",
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable 
```

**Comment by kbseah** [comment]
The lines marked with `#` below in `config/config.yaml` should be indented:

```yaml
dbpaths: # Ref database used by all methods
  sintax:
    bell: #
        "/mnt/raw/databases/metacurated/rbcL_bell.filter.fasta" #
    meta: #
        "/mnt/raw/databases/metacurated/rbcL_metacurator.filter.fasta" #
  multilvl:
```
